server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

service:
  magista:
    url: http://magista:8022/stat
    networkTimeout: 5000

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
info:
  version: '@project.version@'
  stage: dev

keycloak:
  realm: internal
  auth-server-url: http://keycloak:8080/auth/
  resource: common-api
  not-before: 0
  ssl-required: none
  realm-public-key:

auth.enabled: true
